/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutOverlay: typeof import('./src/components/AboutOverlay.vue')['default']
    MeetingCost: typeof import('./src/components/archive/MeetingCost.vue')['default']
    MeetingForm: typeof import('./src/components/MeetingForm.vue')['default']
    MeetingTimerLarge: typeof import('./src/components/MeetingTimerLarge.vue')['default']
    MeetingTimerSmall: typeof import('./src/components/MeetingTimerSmall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timer: typeof import('./src/components/archive/Timer.vue')['default']
  }
}
